CREATE TABLE USER
(
 user_id  INT  AUTO_INCREMENT  PRIMARY KEY COMMENT '',
 name VARCHAR(20) NOT NULL COMMENT '姓名',
 password VARCHAR (20) NOT NULL COMMENT '密码',
 age INT(5) NOT NULL  COMMENT '年龄',
 sex VARCHAR (2) DEFAULT '男' COMMENT '性别',
 create_time DATETIME DEFAULT CURRENT_TIME NULL COMMENT '创建时间',
)
COMMENT '用户表'
ENGINE=innoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 ;

CREATE INDEX user_age ON user(age);